name: Find todos

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  issues: write  # Required for creating GitHub issues

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          CLOSE_ISSUES: "true"